# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Ief's Real IP 2
version: "1.2.1"
slug: ipgetter
description: IP fetch add-on
url: "https://github.com/ivo1981/Ief-s-Real-IP-2/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: before
ports:
  8000/tcp: 8000
map:
  - share:rw
options:
  message: "Hello world..."
  domain: "ief.com"
schema:
  message: "str?"
  domain: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
